//------------------------------------------------------------------------------
// <auto-generated>
//     File: OrderStatus.cs
//     Purpose: This file defines the enum for representing the various statuses 
//     that an order can have throughout its lifecycle.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public enum OrderStatus
{
    Processing,         // Order is being processed
    Shipped,            // Order has been shipped
    PartiallyDelivered, // Some products in the order have been delivered
    Delivered,          // Order has been fully delivered
    Cancelled           // Order has been canceled
}

