//------------------------------------------------------------------------------
// <auto-generated>
//     File: ProductStatus.cs
//     Purpose: This file defines the enum for representing the delivery statuses 
//     of individual products within an order.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public enum ProductStatus
{
    Pending,            // Product is not yet delivered
    PartiallyDelivered, // Part of the order has been delivered
    Delivered,          // Product has been fully delivered
    Cancelled           // Product has been canceled
}
