//------------------------------------------------------------------------------
// <auto-generated>
//     File: CancelOrderRequest.cs
//     Purpose: Defines the structure for canceling an order, including the reason 
//     for cancellation.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public class CancelOrderRequest
{
    public string Note { get; set; }  // Reason for cancellation provided by CSR/Admin
}

