//------------------------------------------------------------------------------
// <auto-generated>
//     File: MarkOrderDeliveredRequest.cs
//     Purpose: Defines the structure for marking an order or part of an order as 
//     delivered, supporting partial deliveries by vendors.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public class MarkOrderDeliveredRequest
{
    public bool PartialDelivery { get; set; }  // Indicates if only a part of the order is delivered
    public string VendorId { get; set; }  // Vendor marking their part of the order as delivered
}

