using System.ComponentModel.DataAnnotations;

//------------------------------------------------------------------------------
// <auto-generated>
//     File: OrderRequest.cs
//     Purpose: Defines the structure for creating a new customer order, including 
//     customer and product details, as well as any special notes.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public class OrderRequest
{
    [Required(ErrorMessage = "CustomerId is required.")]
    public string CustomerId { get; set; }  // ID of the customer placing the order

    [Required(ErrorMessage = "Products are required.")]
    [MinLength(1, ErrorMessage = "At least one product must be included.")]
    public List<OrderProductRequest> Products { get; set; }  // List of products in the order

    public string Notes { get; set; }  // Any special instructions or notes for the order
}


//------------------------------------------------------------------------------
// <auto-generated>
//     File: OrderProductRequest.cs
//     Purpose: Defines the structure for individual products within an order, 
//     including vendor information, quantity, and product status.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public class OrderProductRequest
{
    [Required(ErrorMessage = "ProductId is required.")]
    public string ProductId { get; set; }  // Product ID

    [Required(ErrorMessage = "VendorId is required.")]
    public string VendorId { get; set; }  // Vendor ID

    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1.")]
    public int Quantity { get; set; }  // Quantity of product ordered

    // Add status to track the product's delivery status
    public ProductStatus Status { get; set; }  // Delivery status of the product (e.g., Pending, Delivered)
}
