using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;

//------------------------------------------------------------------------------
// <auto-generated>
//     File: Order.cs
//     Purpose: Represents an order placed by a customer, including product details, 
//     order status, timestamps, and cancellation information.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public class Order
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }  // Unique identifier for the order

    public string CustomerId { get; set; }  // References the customer making the order
    public List<OrderProductRequest> Products { get; set; }  // List of products in the order
    public OrderStatus Status { get; set; }  // Current status of the order

    public string Notes { get; set; }  // Any additional notes for the order

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;  // When the order was created
    public DateTime? UpdatedAt { get; set; }  // Last update time for the order
    public DateTime? DispatchedAt { get; set; }  // When the order was dispatched
    public DateTime? DeliveredAt { get; set; }  // When the order was delivered

    public bool IsCancelled { get; set; } = false;  // Tracks if the order was canceled
    public bool IsPayed { get; set; } = false;  // Tracks if the order has been paid

    public string CancellationNote { get; set; }  // Reason for cancellation provided by CSR/Admin
    public bool IsPartiallyDelivered { get; set; } = false;  // Indicates if the order is partially delivered
}

