//------------------------------------------------------------------------------
// <auto-generated>
//     File: OrderUpdateRequest.cs
//     Purpose: Defines the structure for updating an existing order's product 
//     list and notes before dispatch.
//     Author: Katipearachchi M. E
//     Date: 06/10/2024
// </auto-generated>
//------------------------------------------------------------------------------

public class OrderUpdateRequest
{
    public List<OrderProductRequest> Products { get; set; }  // List of products to update
    public string Notes { get; set; }  // Any additional notes for the order
}

